[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command    = "npm run dev"
  # CHANGE THIS if your Vite dev server is 5190; otherwise leave 5173
  targetPort = 5173
  port       = 8888
  publish    = "dist"
  

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Map all /api/* to Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# SPA fallback — MUST be last
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200